GET http://localhost:3000

###

Get http://localhost:3000/1

###

POST http://localhost:3000
Content-Type: application/json

{
    "author":  "blabla",
	"alt": "blabla",
	"tags": "blabla",
	"image": "blabla",
	"description": "blabla"
}